module Google where
import Test.QuickCheck
import Data.Maybe
-- Feel free to add your own imports (from base and quickCheck packages only!)

-- Imports for harness
import System.Environment (getArgs)
import Control.Exception (handle, throwIO)
import System.IO.Error (isEOFError)
import Data.Function (on)
import Control.Monad (when)
-- import Google (isValidTable)
-- import Google (getKeys)


type Pairs = [(String,FilePath)]     -- Input: Pairs of words and filenames

type Table = [(String, [FilePath])]  -- Association list of words to filenames
{-
    There must be no duplicate keys.
    The keys must be sorted in ascending order.
    There must be no duplicate filenames associated with the same key.
    There must be no empty lists associated with a key.
-}

-- We provide the lookup function for you
basicLookup :: Table -> String -> [FilePath]
basicLookup tab k = fromMaybe [] $ lookup k tab



{-
    Basic assignment: you must implement
-}

{-
    Functions used from Assingments
-}

merge_1 :: Ord a => [a] -> [a] -> [a]
merge_1 [] xs = xs
merge_1 xs [] = xs
merge_1 (x:xs) (y:ys) | x >= y = y : merge_1 (x:xs) (ys)
                     | otherwise = x : merge_1 (xs) (y:ys)

mergeSort :: Ord a => [a] ->[a]
mergeSort [] = []
mergeSort [x] = [x]
mergeSort xs = merge_1 firstHalf secondHalf
   where 
      firstHalf = mergeSort (take (length xs `div` 2 ) (xs))
      secondHalf = mergeSort (drop (length xs `div` 2) (xs))

myElem_2 :: Eq a => a -> [a] -> Bool
myElem_2 m [] = False
myElem_2 m (x:xs) | m == x = True
                | otherwise = myElem_2 m (xs)

dedup :: Eq a => [a] -> [a]
dedup [] = []
dedup (x:xs) | myElem_2 x (xs) == True = dedup (xs)
             | otherwise = x: dedup (xs)


isDistinctNaive :: Eq a => [a] -> Bool
isDistinctNaive [] = True
isDistinctNaive (x:xs) | length (filter (==x) xs) > 0 = False
                    | otherwise = isDistinctNaive xs

-- Functions Implemented for this assignment only (OR there is a change in it) 

-- Removing Duplicate

getItems :: Pairs -> String -> [FilePath]
getItems pairs key = dedup ( map (snd) (filter(\x -> fst x == key ) pairs) ) -- based on the key get all the filepath then remove duplicated and return it as a list of filepath only for one key

getKeys ::  Pairs -> [String]
getKeys [] = []
getKeys (xs) =  dedup (mergeSort (map fst xs)) -- first sort keys (words) then remove duplicated and return it as a list of string

mergeBackPairs :: [String] -> [[FilePath]] -> Table
mergeBackPairs [] [] = []
mergeBackPairs [] _ = []
mergeBackPairs _ [] = []
mergeBackPairs (key : keys) (item : items) = (key, item) : mergeBackPairs (keys) (items)  -- give it a sorted list of name (words) and [items (filepath)] because they have been sorted before (each key has the same index as items ) we merge these keys and items



-- Convert pairs of filenames and words to a table
makeTable :: Pairs -> Table
makeTable [] = []
makeTable (pairs) = mergeBackPairs (getKeys pairs) (map(\key -> getItems pairs key) (getKeys pairs)) -- we use getItems for all the keys we get from getKeys function
-- By using functions like mergeBackPairs we first get the keys sorted and based on them get the items also we remove the duplicate then merge the keys and items together (keys are words and Items are filepath)

{-
    You must also implement:

    a function isValidTable, which checks if a table is valid as described above (no dup keys, no dup filenames, no empty lists)
    a quickCheck property to check that tables generated by your makeTable are valid
-}

isValidTable :: Table -> Bool
isValidTable [] = True
isValidTable tab = (isDuplicatedKeys tab) && (isDuplicatedFilenames tab) && (noEmptyLists tab)   -- Check is there any duplicated keys and is there any duplicated filenames for each key and is there any empty list for each key

isDuplicatedKeys :: Table -> Bool
isDuplicatedKeys [] = True
isDuplicatedKeys (tab) = isDistinctNaive (map fst tab) -- Returns True if there is no duplicated Keys

noEmptyLists :: Table -> Bool
noEmptyLists [] = True
noEmptyLists ((key, filenames):xs) = filenames /= [] && noEmptyLists xs -- return True if there is no empty list for filenames for each key

isDuplicatedFilenames :: Table -> Bool
isDuplicatedFilenames [] = True
isDuplicatedFilenames ((key, filenames):xs) = isDistinctNaive filenames && isDuplicatedFilenames xs -- check there is no duplicated name in filenames for each key

prop_makeTableValid :: Pairs -> Bool
prop_makeTableValid pairs = isValidTable (makeTable pairs) -- Run it for quick check


{-
    Bonus assignment 1:

    Implement a function makeFrequencyTable, that returns an association list mapping each word to
    a list of pairs of filenames and the number how often that word occurs in the filename.
    Sort the values by *decreasing* number of occurrences!


-}

type FrequencyTable = [(String, [(FilePath,Int)])] -- Associate words with filenames and number of occurrences in that file
{-
    There must be no duplicate keys
    There must be no duplicate filenames associated with the same key
    There must be no empty lists associated with a key.
    The lists associated with a key must be sorted in descending order of occurrences

-}

makeFrequencyTable :: Pairs -> FrequencyTable
makeFrequencyTable _ = error "FrequencyTable: not yet implemented"



isValidFrequencyTable :: FrequencyTable -> Bool = error "isValidFrequencyTable: not yet implemented"

prop_makeFrequencyTableValid pairs = error "prop_makeFrequencyTableValid: not yet implemented"


{-
    Bonus assignment 2:

    Are your functions actually correct?

    To be more sure, implement a function directLookup that performs a lookup operation directly on the list of pairs.
    Then write quickCheck tests to compare basicLookup.makeTable and directLookup.

    Do the same for makeFrequencyTable! When checking your submission, we'll run our versions of those tests on your code!
-}




{- ****** Test Harness ******
    We provide a similar test harness as the python assignment:
        Usage: runghc Google.hs <filenames>
        You'll then be prompted for a search term, and it will return the resulting filenames

-}


makePairs :: [FilePath] -> IO Pairs
makePairs args = do
    ftab <- zip args . map words <$> mapM readFile args
    return [ (w,n) | (n,ws) <- ftab, w<-ws ]

prompt :: String -> IO String
prompt msg = do
    putStr $ msg ++ ": "
    handle handler getLine where
        handler e
            | isEOFError e = return ""
            | otherwise    = throwIO e




replLoop :: Table -> IO ()
replLoop tab = go
    where
        go = do
            w <- prompt "Search term"
            if null w then
                return ()
            else do
                let files = basicLookup tab w
                print files
                go



main :: IO ()
main = do
    args <- getArgs
    when (null args) (fail "No filenames provided")

    pairs <- makePairs args
    let tab = makeTable pairs
    replLoop tab

